### ISSUE TITLE
Adding to socialite providers?

### ISSUE THREAD

**Issue by spekulatius** [kylekatarnls/producthunt#1]
Hello @kylekatarnls 

do you think you might be interested in adding this to the [socialite providers](https://github.com/SocialiteProviders/Providers/)?

Cheers,
Peter

**Comment by kylekatarnls** [comment]
It's in yet: https://github.com/SocialiteProviders/Providers/pull/218

**Comment by kylekatarnls** [comment]
Merged in September 2018:
https://socialiteproviders.netlify.com/providers/product-hunt.html

**Comment by spekulatius** [comment]
Ah, okay. Sorry, I've missed that part.
